Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@jhunters 
jhunters
/
timewheel
1
2
0
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
Update go.yml Go #2
Summary
Workflow file
Jobs
build
Workflow file for this run
.github/workflows/go.yml at 85ae0cf
name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic

    - name: CoverageUpload
      run:  bash <(curl -s https://codecov.io/bash)
